TARGET      := save_test
BUILD       := build
LIBBUTANO   := ../../extern/butano/butano
PYTHON      := python
SOURCES     := src ../../extern/butano/common/src ../save_system/src
INCLUDES    := include ../../extern/butano/common/include ../save_system/include
DATA        :=
GRAPHICS    := ../../extern/butano/common/graphics
AUDIO       := ../../extern/butano/common/audio
AUDIOBACKEND := maxmod
AUDIOTOOL   :=
DMGAUDIO    := ../../extern/butano/common/dmg_audio
DMGAUDIOBACKEND := default
ROMTITLE    := SAVE TEST
ROMCODE     := SVTS
USERFLAGS   :=
USERCXXFLAGS :=
USERASFLAGS :=
USERLDFLAGS :=
USERLIBDIRS :=
USERLIBS    :=
DEFAULTLIBS :=
STACKTRACE  :=
USERBUILD   :=
EXTTOOL     :=

ifndef LIBBUTANOABS
	export LIBBUTANOABS := $(realpath $(LIBBUTANO))
endif

include $(LIBBUTANOABS)/butano.mak