TARGET      := battle_ui
BUILD       := build
LIBBUTANO   := ../../extern/butano/butano
PYTHON      := python
SOURCES     := src ../../extern/butano/common/src
INCLUDES    := include ../../extern/butano/common/include ../battle_chatbox/include
DATA        :=
GRAPHICS    := ../../extern/butano/common/graphics
AUDIO       := ../../extern/butano/common/audio
AUDIOBACKEND := maxmod
AUDIOTOOL   :=
DMGAUDIO    := ../../extern/butano/common/dmg_audio
DMGAUDIOBACKEND := default
ROMTITLE    := BATTLE UI
ROMCODE     := BTUI
USERFLAGS   :=
USERCXXFLAGS :=
USERASFLAGS :=
USERLDFLAGS :=
USERLIBDIRS :=
USERLIBS    :=
DEFAULTLIBS :=
STACKTRACE  :=
USERBUILD   :=
EXTTOOL     :=

ifndef LIBBUTANOABS
	export LIBBUTANOABS := $(realpath $(LIBBUTANO))
endif

include $(LIBBUTANOABS)/butano.mak
