TARGET      := scene_manager_test
BUILD       := build
LIBBUTANO   := ../../extern/butano/butano
PYTHON      := python
SOURCES     := src ../../extern/butano/common/src ../../core/src
INCLUDES    := include ../../extern/butano/common/include ../../core/include
DATA        :=
GRAPHICS    := ../../extern/butano/common/graphics
AUDIO       := audio
AUDIOBACKEND := maxmod
AUDIOTOOL   :=
DMGAUDIO    := ../../extern/butano/common/dmg_audio
DMGAUDIOBACKEND := default
ROMTITLE    := SCN MGR TEST
ROMCODE     := SCNT
USERFLAGS   :=
USERCXXFLAGS :=
USERASFLAGS :=
USERLDFLAGS :=
USERLIBDIRS :=
USERLIBS    :=
DEFAULTLIBS :=
STACKTRACE  :=
USERBUILD   :=
EXTTOOL     :=

ifndef LIBBUTANOABS
	export LIBBUTANOABS := $(realpath $(LIBBUTANO))
endif

include $(LIBBUTANOABS)/butano.mak
